### ISSUE TITLE
Poor Intellisense Performance

### ISSUE THREAD

**Issue by cvharris** [buehler/typescript-hero#231]
#### System information

- OS: Mac OSX Sierra
- TypeScript Hero version: 1.1.0
- VSCode version: 1.13.0 & Insiders

#### Description

Trying to use this extension on an Angular-Cli project and noticing a lot of slowdown lately that makes this awesome extension undesirable. It seems the Intellisense is holding things up. I have seen this in the past month and thought it would work itself out.

Whenever I try to start typing for the first time or after blurring and returning to a file (playing with settings/extensions or doing something in Chrome), the first two characters typed triggers the Intellisense and things grind to a halt. Not sure if there's a setting to prevent Intellisense from being triggered after how many keystrokes.

This is an issue with a brand new Angular-Cli project so I think it's pretty reproducible. Hoping it's something to do with just my machine but that's why I'm opening this issue

##### Steps to reproduce

1. Create a new Angular-cli project `ng new derp-project` and open it in VSCode
1. Have every other extensions disabled
2. Wait for TSHResolver to finish building
3. Start typing anything, like `console.log(`
4. Intellisense will hold up at the first character and even potentially on a few subsequent characters
5. Further: create a new service `ng g service derp-service`, then open `app.module.ts` and try typing `DerpService` into the `providers` array. Intellisense is slow on first few characters

**Comment by buehler** [comment]
Well, let's have a look at it. Sometimes I saw messages from the ts-language-server that it crashed on certain ts codes and after that the performance sucked. But in that case, there's nothing we can do in this extension. Lets hope we find the issue..

**Comment by thiagoaos** [comment]
Same here. I disabled the extension temporarily and vscode performance back normal.
Can be a conflict with Angular Language Service extension?

**Comment by cvharris** [comment]
I ruled out any conflicts with other extensions by disabling all but TSH.

**Comment by buehler** [comment]
well right now, TSH "delivers" all calculated symbols each time you change something from the server part to the client part. This needs to change, so that only the deltas are delivered. I'm currently breaking out the parser, so it can be reused in other extensions and projects: https://github.com/TypeScript-Heroes/node-typescript-parser

**Comment by jcjolley** [comment]
FWIW, I too am experiencing this issue, and had to uninstall the extension in order to continue working.
It is also with an Angular-CLI project.

**Comment by buehler** [comment]
I need to check if it's related to https://github.com/Microsoft/vscode/issues/30486

**Comment by cvharris** [comment]
I tried disabling telemetry and it had no effect on the performance impact or delay.

**Comment by Rukenshia** [comment]
Performance severely degraded with the last VS Code update, I don't know if it is VS Code's fault or this plugin, but disabling TS Hero makes the problem (but also the features...) go away.

**Comment by buehler** [comment]
I'm working on a branch to hopefully improve the performance of intellisense.

**Comment by buehler** [comment]
alright, I pushed the branch with a (hopefully) fix to improve the performance.

https://github.com/buehler/typescript-hero/tree/fix/intellisense-performance

I changed a regex test to a string comparison and delayed the calculation of the text edits to a later stage (i.e. when the completion is executed). With that change, the completion items should be calculated faster.

Can you guys test that branch and report if the problem still persists?

(A brief instruction on how to install an extension from scratch: https://github.com/buehler/typescript-hero/issues/194#issuecomment-306134467)

*Note*: When installing the extension from scratch, vscode will try to auto-update it (since the version is 0.0.0 in develop and 1.2.1 published). So you may need to disable auto-update to test it.

Cheers

**Comment by cvharris** [comment]
I can't quite follow your instructions on how to make it work. What should the symlink look like? I did: `ln -s ~/Sites/typescript-hero ~/.vscode/rbbit.typescript-hero-0.0.0` where `~/Sites/typescript-hero` is where I cloned the branch and built it. I moved the old folder out. In VSCode it still has the performance issue but says the version of the extension is 1.2.1

**Comment by buehler** [comment]
Uhm, well them you need (assuming your setup) to do:
```bash
cd ~/.vscode/extensions
rm -rf rbbit.typescript-hero*
cd ~/Sites/typescript-hero
npm install
npm run build
cd ~/.vscode/extensions
ln -s ~/Sites/typescript-hero
```

This removes the installed version of typescript hero (you can do it manually via the vscode extensions gui), then builds the repo, and creates the symlink to the built extension.

**Comment by cvharris** [comment]
Ok thanks. I'm still not sure if I'm serving up the right version because it says 1.2.1 in the extensions sidebar still. There isn't any change in performance either. I may be loading your branch wrong though. Wish I could test this out.

**Comment by jcjolley** [comment]
@buehler I can confirm that the fix branch fixes the issue. Intellisense is fast and helpful again.
Thank you so much for your hard work!

![8e711676-89a1-428d-9134-5b645d64dec8](https://user-images.githubusercontent.com/2086176/28220062-56de2880-687b-11e7-9111-d9bca72abc11.gif)

**Comment by buehler** [comment]
@jcjolley cool! :-) so lets deploy that thing..

**Comment by cvharris** [comment]
Much better performance. Thanks for your fix @buehler!

**Comment by lednhatkhanh** [comment]
Can confirm that the intellisense performance is terribly slow with this extension enabled, disabled it makes vscode fast again...

**Comment by smasherprog** [comment]
same here. I had to disable this plugin at work because intellsense was unusable.

**Comment by gergoszucs** [comment]
Are there any plans to fix this issue? The plugin would be so useful, but as of now it makes VSCode almost unusable, the whole team had to disable it.

**Comment by buehler** [comment]
@gergoszucs 
Sadly, I've hardly the time to code at my side projects right now.
Another point is: I need to wait for the next vscode release, since they actually add all the features to it that my extension does. So when this release hits production, I probably discontinue the plugin or disable everything despite the import grouping / sorting.

**Comment by gergoszucs** [comment]
@buehler Honestly, we would be only using the import sorting feature anyway. I just can't find any other extension which would have the same level of customization. What TSHero offers (import grouping, predefined regexes etc) is really great. If you'll have the time, I'm sure most of us would love to see that functionality in a standalone module.

On a side note, I'd like to propose a new feature. When the line length threshold is surpassed, it would be nice to customize, whether we want a line-by-line break or just split the line of imports into the least possible lines (so you'd split it at the last possible import then continue the list in the next line).

I've checked the VSCode import organization feature, it isn't really what TSHero has been offering.

**Comment by buehler** [comment]
@gergoszucs 
That's nice to hear :)
I'll have a look as soon as the VSCode release comes out.

For the feature, I thought, it's already present, but I'll have a look at it!
Thanks for the feedback
