### ISSUE TITLE
Put lower priority for typeahead completion in property name

### ISSUE THREAD

**Issue by n00dl3** [buehler/typescript-hero#67]
When typing the name of a property in an object declaration (in order to pass it to a function that expects a certain interface), the hints for importing a class/interface/whatever comes prior the ones for the  property.

The hovered one is what I want to insert and the first ones are from the import suggestions:
![screenshot](http://s11.postimg.org/5oqi3xawj/2016_09_23_122758_5760x1080_scrot.png)

I don't know if it is possible with vs-code API to use a custom priority for hinting but in this case the property hint should be displayed first.

BTW: 0.7.1 is awesome !

**Comment by buehler** [comment]
@n00dl3 Thanks :-)

I don't think I can lower the priority. What I could do is sorting them to the bottom. But I fixed some bugs for the auto completion, so actually should not suggest stuff that is already imported or in your own file.

Would you mind to check that out? =)
(master branch)

Cheers

**Comment by n00dl3** [comment]
I'll test that this weekend, I'm in a hurry right now :tired_face: !

**Comment by buehler** [comment]
No worries ;-)

**Comment by buehler** [comment]
Hey @n00dl3 got a chance to check it with the new and shiny 0.8.0 version?

**Comment by n00dl3** [comment]
Oh sorry, I forgot that.
yup, still the same with 0.8... :disappointed:

**Comment by buehler** [comment]
Well I'll have a look at that. VSCode did something to this priority stuff, but I don't know if it's solving your / our problem..
